### ISSUE TITLE
Problem getting caddy2 to work with sslh

### ISSUE THREAD

**Issue by otbutz** [caddyserver/caddy#3232]
I'm trying to setup the current v2.0-rc1 behind sslh in order to use port 443 for openvpn and https.

sslh is configured to listen only on the **external** IPv4 and IPv6 addresses:

`ss -tln`:
```
State                        Recv-Q                         Send-Q                                                            Local Address:Port                                                 Peer Address:Port                        
LISTEN                       0                              50                                                                 192.168.1.26:80                                                        0.0.0.0:*                           
LISTEN                       0                              50                                                                 192.168.1.26:443                                                       0.0.0.0:*                           
LISTEN                       0                              50                                                      [2001:xxx:xxx:xxx::13]:80                                                           [::]:*                           
LISTEN                       0                              50                                                      [2001:xxx:xxx:xxx::13]:443                                                          [::]:*
```

My Caddfile:
```
{
	email john.doe@example.org
	acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
}

(common) {
	bind 127.0.0.1 ::1
}

git.example.org {
	import common
	reverse_proxy git.local
}

web.example.org {
	import common
	reverse_proxy web.local
}
```

Ports used by caddy(without sslh running):
```
State                          Recv-Q                          Send-Q                                                    Local Address:Port                                                    Peer Address:Port                          
LISTEN                         0                               128                                                           127.0.0.1:443                                                          0.0.0.0:*                             
LISTEN                         0                               128                                                               [::1]:80                                                              [::]:*                             
LISTEN                         0                               128                                                               [::1]:443                                                             [::]:*    
```
My first observation is that caddy is not binding on `127.0.0.1:80` although nothing else is blocking this port. I already executed `ss` with root priviliges and couldn't find any other service blocking port 80. 

And i found this in the logs(Redacted the domain):
```log
Apr 06 14:34:15 proxy caddy[3328]: [openvpn.example.org] [openvpn.example.org] acme: error presenting token: presenting with embedded provider: could not start listener at :80 for challenge server: listen tcp :80: bind: address already in use
Apr 06 14:34:15 proxy caddy[3328]:  (challenge=http-01 remaining=[tls-alpn-01])
```

Note: i have not forwarded my external ports(80/443) to sslh yet and fully expected that the ACME challenge would fail but the port binding should have worked properly nevertheless.

**Comment by mholt** [comment]
@otbutz You might be hitting this same problem: https://caddy.community/t/v2-upgrade-to-caddy2-failing-with-errors/7423?u=matt

The OS is reporting contradictory information as far as we can tell. (Read that thread for more info.) I've hacked around it in the latest commits. Can you download the latest build artifacts and try again? (see the Actions tab)

**Comment by otbutz** [comment]
> Can you download the latest build artifacts and try again?

I've checked with the last one which was built from `master`: https://github.com/caddyserver/caddy/actions/runs/70712155

Same problem

**Comment by mholt** [comment]
@otbutz Can you please double-check that you're using the right binary?

**Comment by otbutz** [comment]
Thank you, i was indeed using the old binary.

```
Apr 06 16:39:45 proxy caddy[3706]: 2020/04/06 16:39:45 [WARNING] OS reports a contradiction: listen tcp :80: bind: address already in use - but we cannot connect to it, with this error: dial tcp :80: connect: connection refused;  continuing anyway <F0><9F><A4><9E>
```

But it's still not binding to `127.0.0.1:80`

It looks like caddy binds successfully to the IPv6 loopback address on port 80 and tries to create a global port binding on 80 afterwards.

The strange thing is that if i switch to `bind 127.0.0.1` the same thing happens which makes no sense to me. Why would caddy bind to ::1 if i specify a IPv4 address for `bind`?

**Comment by mholt** [comment]
Thanks for double-checking!

> Why would caddy bind to ::1 if i specify a IPv4 address for bind?

That hasn't been implemented yet.

At least, not in the Caddyfile. I just pushed a commit in 6a32daa that lets you customize it via JSON. You could pull that down (or use its build artifact) while I work on Caddyfile support for that.

**Comment by mholt** [comment]
@otbutz Okay, I have pushed a commit that should carry your `bind` preferences through to the ACME solver. I have tested it a little bit but not with your particular setup, could you please try it out and confirm?

Thanks!

**Comment by otbutz** [comment]
Still the same :(

Additional to that it looks like caddy doesn't pick up the changes in the Caddyfile. I've removed the local binding and restarted the service and it's still binding to loopback. I even executed `killall caddy` as root user and restarted the service.

It seems to me that it still uses the values from `/var/lib/caddy/.config/caddy/autosave.json`:

```json
{"apps":{"http":{"servers":{"srv0":{"listen":["127.0.0.1:443","[::1]:443"],"routes":[{"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"web.local:"}]}]}]}],"match":[{"host":["web.example.org"]}],"terminal":true},{"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"git.local:"}]}]}]}],"match":[{"host":["git.example.org"]}],"terminal":true}]}}},"tls":{"automation":{"policies":[{"issuer":{"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","email":"hostmaster@example.org","module":"acme"}}]}}}}
```

**Comment by otbutz** [comment]
After deleting `autosave.json` and restarting caddy it has picked up the Caddyfile changes and binds globally now. I'm going to restore the loopback binding configuration and start the service without an existing autosave.json and see if anything changes.

**Comment by otbutz** [comment]
This is getting weird...

Using `bind 127.0.0.1 ::1`

netstat:
```
tcp        0      0 127.0.0.1:443           0.0.0.0:*               LISTEN      4492/caddy          
tcp        0      0 127.0.0.1:2019          0.0.0.0:*               LISTEN      4492/caddy          
tcp6       0      0 ::1:80                  :::*                    LISTEN      4492/caddy          
tcp6       0      0 ::1:443                 :::*                    LISTEN      4492/caddy
```

autosave.json:
```
"listen":["127.0.0.1:443","[::1]:443"]
...
"challenges":{"bind_host":"127.0.0.1"}
```

Using `bind ::1 127.0.0.1`

netstat:
```
tcp        0      0 127.0.0.1:80            0.0.0.0:*               LISTEN      4546/caddy          
tcp        0      0 127.0.0.1:443           0.0.0.0:*               LISTEN      4546/caddy          
tcp        0      0 127.0.0.1:2019          0.0.0.0:*               LISTEN      4546/caddy          
tcp6       0      0 ::1:443                 :::*                    LISTEN      4546/caddy
```

autosave.json:
```
"listen":["[::1]:443","127.0.0.1:443"]
...
"challenges":{"bind_host":"::1"}
```

Shouldn't caddy listen on IPv4 and IPv6 for challenges?

**Comment by mholt** [comment]
Actually this isn't surprising, since CertMagic can only bind one listener for the challenge, so we have to pick one interface. We just happen to use the first one. 🤷‍♂

Also:

> After deleting autosave.json and restarting caddy

You are probably using the `--resume` flag, which tells Caddy to resume from the last saved configuration. (Don't restart the web server to reload config, it results in downtime!)

**Comment by otbutz** [comment]
> Actually this isn't surprising, since CertMagic can only bind one listener for the challenge, so we have to pick one interface. We just happen to use the first one. man_shrugging

That makes sense. I'm going to stick with globally bound ports for caddy then and use port 8443 with a firewall rule for sslh.

> Also:
> 
> > After deleting autosave.json and restarting caddy
> 
> You are probably using the `--resume` flag, which tells Caddy to resume from the last saved configuration. (Don't restart the web server to reload config, it results in downtime!)

IMHO this behavior of the caddy systemd unit violates the principle of least surprise. Most admins are going to expect that a `systemctl restart caddy` will cause configuration changes to be applied.

**Comment by mholt** [comment]
> Most admins are going to expect that a systemctl restart caddy will cause configuration changes to be applied.

You're not the first to say that. :) We have a whole big discussion going on about that right now here: https://github.com/caddyserver/dist/pull/16

However, using `restart` to both stop and start the server _and_ change its configuration is dangerous.

> this behavior of the caddy systemd unit violates the principle of least surprise.

Then change it to meet your preferences.

If you think about it, though, stopping the server is not a good way to reload configuration, and the two are totally separate tasks.

- Stop the process to install security updates that require a system reboot, for example
- Reload the configuration deliberately only when you are ready to apply an updated config

Recovering from a power cycle and inadvertently changing the configuration at the same time is dangerous, and if the config API is used during the lifetime of the server, can even lead to data loss and serving the site in an inconsistent state. A machine should _always_ be able to be reliably rebooted and the server should _always_ be able to come back online as it was before.

Caddy makes these guarantees with our standard unit file. It's just old, bad habits that die hard...

**Comment by otbutz** [comment]
> it's just old, bad habits that die hard

There's a difference between old habits and de facto standards. Off the top of my head I couldn't name a service that wouldn't reload its configuration on restart.

IMHO the main problem is that the default unit file cannot cover both configuration mechanisms. Removing the `--resume` option is perfectly fine if i don't want to use the dynamic configuration feature.

**Comment by mholt** [comment]
> There's a difference between old habits and de facto standards. Off the top of my head I couldn't name a service that wouldn't reload its configuration on restart.

"De facto standards" are not something we're trying to imitate in this project, though. And to be fair/honest, I don't care if other services do this. I've always thought this is a bad idea. You're welcome to do it if you want to, though! No judgment here, I just don't want to propagate what I think are unstable methods.

> IMHO the main problem is that the default unit file cannot cover both configuration mechanisms.

It can, just use `reload` instead of `stop` (stopping the service will take your site offline).

> Removing the --resume option is perfectly fine if i don't want to use the dynamic configuration feature.

Generally yes, but again it depends how durable and reliable you need your deployment to be, and what kind of environmental factors there are. For example, some people don't want a config to be changed when its file changes -- I for one will save quite often when editing a file, especially while putting out fires in production, the last thing I need is for a config change to be applied that isn't ready yet. I've also heard and read accounts from people using Caddy and other web servers of similar sentiments. Changing config is not to be taken lightly sometimes!

But if it works for you, then that's great! No problem.
