### ISSUE TITLE
Forcing Scheme and Port to Match

### ISSUE THREAD

**Issue by vtky** [caddyserver/caddy#3361]
Hello!

I'd like to find out the rationale for the following code

https://github.com/caddyserver/caddy/blob/afecd90a6ca1551057631d21d940af86385ac535/modules/caddyhttp/reverseproxy/caddyfile.go#L121

It forces http to match port 80 and https to match 443 and there is no way to overwrite if I want to run https on port 80. (unless I'm missing something?)

**Comment by mholt** [comment]
Configuration for the reverse proxy transport is inferred from the upstream address; if it's a "plain" network address (e.g. socket) we use it literally; if it's a URL, we can draw from the different components like scheme and port, so that if you specify `https://` we can enable TLS to the upstream implicitly.

But it's problematic if you specify a scheme that says "use TLS" with a port that says "don't use TLS."

Why do you want to run HTTPS on port 80? AFAIK I that defies IANA conventions and expected behavior pretty much everywhere. We want networks to be compatible....

You _can_ do this, of course, but not with implicit means, since the conflict leaves it ambiguous.

(Hopefully that answers your question! I will close the issue but feel free to continue discussion.)

**Comment by vtky** [comment]
@mholt Thanks for that! Unfortunately I'm proxying an application that performs SSL on port 80. For now, I'm going to do a custom build of Caddy. Would you and the team consider an option to force an overwrite, if I were to write a patch and submit it?

**Comment by mholt** [comment]
You can already do this:


```
reverse_proxy localhost:80 {
    transport http {
        tls
    }
}
```

At least, I think that'll work. (It's just weird.)

**Comment by vtky** [comment]
Caddy spits out a parsing error.

`upstream address scheme is HTTP but transport is configured for HTTP+TLS (HTTPS)`

**Comment by mholt** [comment]
Hmm, I see... I've pushed a fix to master in 1c17e5c @vtky - can you please try it and confirm?

Basically, if a scheme is given explicitly, it must not conflict with port convention, but if the scheme is omitted, i.e. what I showed above, it should work, since there's nothing implicit/hidden going on there.

**Comment by vtky** [comment]
Not sure what went wrong but it still failed. I had to comment out https://github.com/caddyserver/caddy/blob/1c17e6c6bb30f730581708d9725aab7ca0a8c560/modules/caddyhttp/reverseproxy/caddyfile.go#L552 to L554

Then it works for me.

**Comment by mholt** [comment]
@vtky are you sure you tried the version from that commit? It worked for me.
