### ISSUE TITLE
"auto_https off" not honoured in certain cases

### ISSUE THREAD

**Issue by tkaehn** [caddyserver/caddy#4667]
I noticed Caddy trying to connect to Let's Encrypt and ZeroSSL despite auto_https set to off
with a more complex configuration.

The following reduced examples show that automate is active for one domain name when using Caddyfile3:

```
# caddy version
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
```

```
# cat Caddyfile1 
{
	auto_https off
}

https://

tls test.crt test.key

respond "Hello World"


# caddy adapt -pretty -config Caddyfile1 | grep -C 3 automate
# (no output)
```

```
# cat Caddyfile2
{
	auto_https off
}

https://example.com

tls test.crt test.key

respond "Hello World"


# caddy adapt -pretty -config Caddyfile2 | grep -C 3 automate
# (no output)
```

```
# cat Caddyfile3
{
	auto_https off
}

https://example.com,
https://

tls test.crt test.key

respond "Hello World"


# caddy adapt -pretty -config Caddyfile3 | grep -C 3 automate
		},
		"tls": {
			"certificates": {
				"automate": [
					"example.com"
				],
				"load_files": [
# 
```

**Comment by francislavoie** [comment]
Please try with a build from master, it's possible we've already fixed these issues.

**Comment by tkaehn** [comment]
Please see the output below. From the output I'd guess the problem isn't fixed (however I didn't check if connections to Let's Encrypt/ZeroSSL are made or not):

```
$ git log -n 1
commit 734acc776a1156d22dabedd420053d834663a22e (HEAD -> master, origin/master, origin/HEAD)
Author: Francis Lavoie <lavofr@gmail.com>
Date:   Mon Mar 28 17:07:43 2022 -0400

    chore: Fix for xcaddy builds (#4665)
    
    * chore: Attempt fix for xcaddy builds
    
    * Upgrade smallstep/certificates which avoids the problem

$ ./caddy version
(devel)

$ ./caddy adapt -pretty -config Caddyfile3 | grep -C 3 automate
		},
		"tls": {
			"certificates": {
				"automate": [
					"example.com"
				],
				"load_files": [
$ 
```

**Comment by francislavoie** [comment]
For now, just split those up into two separate site blocks.

I'm not sure it really makes sense to have `https://` and `https://example.com` in the same site block, it's redundant.

Either way, it's an edgecase that should be covered, I guess.

**Comment by tkaehn** [comment]
Yes, for now I live with `https://` as it covers `https://example.com` as well. But I agree with you that this is a bug.

**Comment by francislavoie** [comment]
Proposed fix in https://github.com/caddyserver/caddy/pull/5110

Essentially, it skips adding anything to `automate` entirely when `auto_https off` is set.
