### ISSUE TITLE
Caddyfile: try_files =404 breaks error template

### ISSUE THREAD

**Issue by bones-was-here** [caddyserver/caddy#4968]
According to https://caddyserver.com/docs/caddyfile/directives/php_fastcgi#examples a 404 can be returned instead of rewriting to `index.php` when the requested file doesn't exist, and this may be handled by `handle_errors`.  However this breaks the error template configured in `handle_errors` (which is working well for other sources of errors).  

The client gets an empty body or a weird message (from FPM?) and caddy logs "error handling handler error".  These errors vary somewhat depending what exactly was requested, sometimes it will fail to execute the template "error calling httpInclude: http 404".

Breaks:
```
php_fastcgi unix//run/php/php-fpm.sock {
	try_files {path} {path}/index.php =404
}
```
Works for non-php files but proxies requests for .php files that don't exist to PHP:
```
php_fastcgi unix//run/php/php-fpm.sock {
	try_files {path} {path}/index.php
}
```
Breaks (php_fastcgi expanded form, with =404):
```
(my_php) {
	# Add trailing slash for directory requests
	@canonicalPath {
		file {path}/index.php
		not path */
	}
	redir @canonicalPath {path}/ 308

	# If the requested file does not exist, try index files
	@indexFiles file {
		try_files {path} {path}/index.php =404
		split_path .php
	}
	rewrite @indexFiles {http.matchers.file.relative}

	# Proxy PHP files to the FastCGI responder
	@phpFiles path *.php
	reverse_proxy @phpFiles {args.0} {
		transport fastcgi {
			split .php
		}
	}
}
```
Working properly:
```
(my_php) {
	@canonicalPath {
		file {path}/index.php
		not path */
	}
	redir @canonicalPath {path}/ 308

	try_files {path} {path}/index.php

	@php {
		path *.php
		file
	}
	reverse_proxy @php {args.0} {
		transport fastcgi {
			split .php
		}
	}
}
```

**Comment by francislavoie** [comment]
Which version is this with?

Can you try a build from the master branch? I think we've fixed this somewhat recently.

**Comment by bones-was-here** [comment]
Sorry that was 2.5.2.  I'm testing master (fe5f5dfd6aa2f48e92897327c9c7d8c8583a3d72) and it looks like it's partially fixed.  

Working (fixed):
```
php_fastcgi unix//run/php/php-fpm.sock {
	try_files {path} {path}/index.php =404
}
```
Still broken (caddy logs internal 500 error rendering template and "error calling httpInclude: http 404", client sees 404 status with 0 byte body):
```
(my_php) {
	# Add trailing slash for directory requests
	@canonicalPath {
		file {path}/index.php
		not path */
	}
	redir @canonicalPath {path}/ 308

	# If the requested file does not exist, try index files
	@indexFiles file {
		try_files {path} {path}/index.php =404
		split_path .php
	}
	rewrite @indexFiles {http.matchers.file.relative}

	# Proxy PHP files to the FastCGI responder
	@phpFiles path *.php
	reverse_proxy @phpFiles {args.0} {
		transport fastcgi {
			split .php
		}
	}
}
```
Still working:
```
(my_php) {
	@canonicalPath {
		file {path}/index.php
		not path */
	}
	redir @canonicalPath {path}/ 308

	try_files {path} {path}/index.php

	@php {
		path *.php
		file
	}
	reverse_proxy @php {args.0} {
		transport fastcgi {
			split .php
		}
	}
}
```

**Comment by francislavoie** [comment]
I'm pretty sure the wrapping `route` matters when you're using the expanded form, otherwise the directives might get sorted elsewhere in the middleware chain after importing, according to the directive order https://caddyserver.com/docs/caddyfile/directives#directive-order

Looks like this is solved.

**Comment by bones-was-here** [comment]
I re-tested with the `route` block included in the snippet, and it does indeed fix the expanded form (on fe5f5dfd6aa2f48e92897327c9c7d8c8583a3d72).  
To me that seems like a bug because the directive order as written is  
1. `redir`
2. `rewrite`
3. `reverse_proxy`

Which is the same as the documented default directive order.  So why does adding a `route` block (no other changes) change the result?

**Comment by bones-was-here** [comment]
Oh mybad the import is not evaluated as a unit, it's more like a copy paste followed by normal evaluation.

**Comment by francislavoie** [comment]
Exactly, `import` is just fancy copy-paste.
