### ISSUE TITLE
Caddy tries to provision local CA and write to /data/caddy/pki even with auto_https off and skip_install_trust

### ISSUE THREAD

**Issue by GreyXor** [caddyserver/caddy#7211]
Hi,

I’m running Caddy 2.10 inside a Docker container (via FrankenPHP) with this config : 

`frankenphp run --config /etc/frankenphp/Caddyfile`
```
{
	admin off
	auto_https off
	skip_install_trust

	frankenphp

	servers {
		protocols h1 h2c
		enable_full_duplex
	}
}

http:// {
	root /var/www/html

	encode

	php_server {
	    try_files {path} {path}/ /index.php{uri}
		resolve_root_symlink false
		root /var/www/html
	}
}
```

log 

```bash
{"level":"info","ts":1756126785.7373068,"msg":"using config from file","file":"/etc/frankenphp/Caddyfile"}
{"level":"warn","ts":1756126785.7379525,"logger":"admin","msg":"admin endpoint disabled"}
{"level":"info","ts":1756126785.738021,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
{"level":"debug","ts":1756126785.7380357,"logger":"http.auto_https","msg":"adjusted config","tls":{"automation":{"policies":[{}]}},"http":{"servers":{"srv0":{"listen":[":80"],"enable_full_duplex":true,"routes":[{"handle":[{"handler":"vars","root":"/var/www/html"},{"encodings":{"gzip":{},"zstd":{}},"handler":"encode","prefer":["zstd","gzip"]}]},{"handle":[{"handler":"rewrite","uri":"{http.matchers.file.relative}"}]},{"handle":[{"handler":"php","resolve_root_symlink":false,"root":"/var/www/html","split_path":[".php"]}]},{"handle":[{"handler":"file_server","root":"/var/www/html"}]}],"automatic_https":{"disable":true},"protocols":["h1","h2c"]}}}}
{"level":"info","ts":1756126785.738101,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000665780"}
{"level":"info","ts":1756126785.739171,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc000665780"}
{"level":"info","ts":1756126785.7391992,"msg":"maxprocs: No GOMAXPROCS change to reset"}
Error: loading initial config: loading new config: loading pki app module: provision pki: provisioning CA 'local': generating root: saving root certificate: mkdir /data/caddy/pki: permission denied
```

```bash
www-data@a7bda8870145:/data/caddy/pki/authorities/local$ ls -lah
total 16K
drwx------ 1 www-data www-data  96 Aug 25 13:05 .
drwx------ 1 www-data www-data  10 Aug 25 13:05 ..
-rw------- 1 www-data www-data 676 Aug 25 13:05 intermediate.crt
-rw------- 1 www-data www-data 227 Aug 25 13:05 intermediate.key
-rw------- 1 www-data www-data 627 Aug 25 13:05 root.crt
-rw------- 1 www-data www-data 227 Aug 25 13:05 root.key
```

Since TLS is fully handled upstream by Traefik, I don’t want Caddy to touch HTTPS/TLS/PKI at all. However, even with auto_https off and skip_install_trust, Caddy still tries to generate a local root CA and write certificates under /data/caddy/pki/.

This happens right at startup. The only way to bypass it is to chown -R www-data:www-data /data/caddy/, which then results in root.crt, root.key, intermediate.crt, and intermediate.key being generated under /data/caddy/pki/authorities/local/.

More context:
- https://gitlab.com/greyxor/nextcloud-docker/-/tree/feat-caddy-frankenphp

**Comment by mholt** [comment]
`skip_install_trust` just skips installing the CA into the trust store(s), it doesn't skip generating them.

That said, the error really should be resolved. Caddy will need permission to write to its data directory.

**Comment by GreyXor** [comment]
Alright! I thought that `auto_https off` would disable any HTTPS/TLS features. i'm not sure why caddy need to generate these CA and keys.

**Comment by francislavoie** [comment]
@mholt you missed that there's a `"logger":"http.auto_https","msg":"adjusted config"` even though there's `auto_https off`, that shouldn't happen at all, that's the bug.

**Comment by mholt** [comment]
Ah, I see... will look into it.

**Comment by Siomachkin** [comment]
The issue occurs in two separate locations where PKI infrastructure is created even when `auto_https off` is specified:

 **1. `automaticHTTPSPhase1()` continues execution after disabled servers**

In `modules/caddyhttp/autohttps.go`, the function processes each server in a loop, but continues executing after the loop even when all servers have `auto_https off`:

```go
// Current problematic flow:
for srvName, srv := range app.Servers {
    if srv.AutoHTTPS.Disabled {
        logger.Info("automatic HTTPS is completely disabled")
        continue  // <- Only skips THIS server
    }
    // ... process server
}
// <- Code continues here always, creating TLS automation policies
err := app.createAutomationPolicies(ctx, internal, tailscale)  // Creates PKI
logger.Debug("adjusted config")  // Logs even when disabled
```

 **2. `skip_install_trust` forcibly creates PKI regardless of `auto_https`**

In `caddyconfig/httpcaddyfile/pkiapp.go`, the `skip_install_trust` directive unconditionally creates PKI even with `auto_https off`:

```go
// Current problematic logic:
if len(pkiApp.CAs) == 0 && skipInstallTrust {
    ca := new(caddypki.CA)  // <- Creates PKI even with auto_https off
    ca.ID = caddypki.DefaultCAID
    pkiApp.CAs[ca.ID] = ca
}
```
---

**Proposed Fix**

**Fix 1: Early return in `automaticHTTPSPhase1()`**

Add a check after the server loop to exit early when all servers disable auto HTTPS:

```go
// After the server processing loop:
allServersDisabled := true
for _, srv := range app.Servers {
    if srv.AutoHTTPS == nil || !srv.AutoHTTPS.Disabled {
        allServersDisabled = false
        break
    }
}
if allServersDisabled && len(uniqueDomainsForCerts) == 0 {
    logger.Debug("all servers have automatic HTTPS disabled, skipping TLS automation setup")
    return nil  // <- Prevents TLS automation creation
}
```

**Fix 2: Respect `auto_https` in `skip_install_trust` logic**

Check `auto_https off` before creating PKI for `skip_install_trust`:

```go
// In buildPKIApp(), check auto_https setting:
autoHTTPS := []string{}
if ah, ok := options["auto_https"].([]string); ok {
    autoHTTPS = ah
}
autoHTTPSOff := slices.Contains(autoHTTPS, "off")

// Modified condition:
if len(pkiApp.CAs) == 0 && skipInstallTrust && !autoHTTPSOff {
    ca := new(caddypki.CA)
    ca.ID = caddypki.DefaultCAID
    ca.InstallTrust = &falseBool
    pkiApp.CAs[ca.ID] = ca
}
```

**Comment by francislavoie** [comment]
Sounds good to me! Feel free to make a PR to fix it 👍
